### ISSUE TITLE
Ошибка при деплое, не описанная в инструкции

### ISSUE THREAD

**Issue by pablo071** [worksolutions/deployment-assistant#2]
-bash-4.1$ php ./dep.phar deploy
Checking that the work dir has no changes...fatal

                                                                                           
  [Symfony\Component\Process\Exception\RuntimeException]                                   
  The Process class relies on proc_open, which is not available on your PHP installation.  
                                                                                           

deploy [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> [<remote>] [<branch>]

**Comment by dsxack** [comment]
Потребуется написать адаптер, когда недоступна функция proc_open использовать exec.

Так же, придется отказаться от библиотеки symfony/process

**Comment by dsxack** [comment]
Ошибка исправлена. Документация обновлена, нужно запускать деплоер с параметром `-d disabled_functions=""`
