### ISSUE TITLE
Ошибка загрузки деплоера на сервер

### ISSUE THREAD

**Issue by DanielAkinfeev** [worksolutions/deployment-assistant#5]
при выполнении команды php -r "copy('http://dep.worksolutions.ru/dep.phar', 'dep.phar');"

получаю следующее:

Warning: copy(http://dep.worksolutions.ru/dep.phar): failed to open stream: No such file or directory in Command line code on line 1

**Comment by dsxack** [comment]
Исправил документацию. Теперь нужно вызывать команду так:
`php -d allow_url_fopen=1 -r "copy('http://dep.worksolutions.ru/dep.phar', 'dep.phar');"`
